# Generated by Django 4.2.6 on 2023-10-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.shelf'),
            preserve_default=False,
        ),
    ]
