# Generated by Django 4.2.6 on 2023-11-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_user_shelf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
